#after uploading it i'm not able to upload firmware to the second esp by wireless but connectivity with ha works for me
esphome:
  name: esp32u4audioside
  friendly_name: esp32u4audioside
  on_boot:
    priority: 600
    then:
      - output.turn_on: mute
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ""
    password: ""

captive_portal:
i2s_audio:
  - id: i2sout
    i2s_lrclk_pin: GPIO27
    i2s_bclk_pin: GPIO25

media_player:
  - platform: i2s_audio
    dac_type: external
    i2s_dout_pin: GPIO26
    mode: stereo
    id: mp
    i2s_audio_id: i2sout
    name: "PLAYER"
output:
  - platform: gpio
    pin: GPIO32
    id: mute
